version: '3.2'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    ports:
      - "5601:5601"

  fluentd:
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  configurationservice:
    build:
      context: ./configuration-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "7777:7777"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: configurationservice

  eureka:
    build:
      context: ./discovery-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8761:8761"
    depends_on:
      - configurationservice
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: eureka

  zuul:
    build:
      context: ./zuul-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - configurationservice
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: zuul

  hystrixdashboard:
    build:
      context: ./hystrix-dashboard
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8766:8766"
    depends_on:
      - eureka
      - configurationservice
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: hystrixdashboard

  excelexportservice:
    build:
      context: ./excel-export-service
      dockerfile: /docker/Dockerfile.dist
    depends_on:
      - eureka
      - configurationservice
      - zuul
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: excelexportservice

  parkinglotservice:
    build:
      context: ./parking-lot-service
      dockerfile: /docker/Dockerfile.dist
    depends_on:
      - eureka
      - configurationservice
      - zuul
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: parkinglotservice

  parkingspotwebapp:
    build:
      context: ./parking-spot-for-me-webapp
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8080:8080"
    depends_on:
      - parkinglotservice
      - eureka
      - configurationservice
      - zuul
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: parkingspotwebapp

  adminservice:
    build:
      context: ./admin-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "1111:1111"
    depends_on:
      - eureka
      - configurationservice
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: adminservice
  zipkin:
    build:
      context: ./zipkin-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "9411:9411"
    depends_on:
      - eureka
      - configurationservice
      - fluentd
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: zipkin