version: '3.2'

services:
  configurationservice:
    build:
      context: ./configuration-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "7777:7777"

  eureka:
    build:
      context: ./discovery-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8761:8761"
    depends_on:
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777

  zuul:
    build:
      context: ./zuul-service
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  hystrixdashboard:
    build:
      context: ./hystrix-dashboard
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8766:8766"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  excelexportservice:
    build:
      context: ./excel-export-service
      dockerfile: /docker/Dockerfile.dist
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  parkinglotservice:
    build:
      context: ./parking-lot-service
      dockerfile: /docker/Dockerfile.dist
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  parkingspotwebapp:
    build:
      context: ./parking-spot-for-me-webapp
      dockerfile: /docker/Dockerfile.dist
    ports:
      - "8080:8080"
    depends_on:
      - parkinglotservice
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka