version: '3.2'

services:
  configurationservice:
    build: ./configuration-service
    ports:
      - "7777:7777"

  eureka:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777

  zuul:
    build: ./zuul-service
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
      
  hystrixdashboard:
    build: ./hystrix-dashboard
    ports:
      - "8766:8766"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  excelexportservice:
    build: ./excel-export-service
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka


  parkinglotservice:
    build: ./parking-lot-service
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka
