version: '3.2'

services:
  configurationservice:
    image: patrykks/iosr-configuration-service
    ports:
      - "7777:7777"

  eureka:
    image: patrykks/iosr-discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777

  zuul:
    image: patrykks/iosr-zuul-service
    ports:
      - "8765:8765"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  hystrixdashboard:
    image: patrykks/iosr-hystrix-dashboard
    ports:
      - "8766:8766"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  excelexportservice:
    image: patrykks/iosr-excel-export-service
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  parkinglotservice:
    image: patrykks/iosr-parking-lot-service
    depends_on:
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  parkingspotwebapp:
    image: patrykks/iosr-parking-spot-webapp
    ports:
      - "8080:8080"
    depends_on:
      - parkinglotservice
      - eureka
      - configurationservice
      - zuul
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  adminservice:
    image: patrykks/iosr-admin-service
    ports:
      - "1111:1111"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka

  zipkin:
    image: patrykks/iosr-zipkin-service
    ports:
      - "9411:9411"
    depends_on:
      - eureka
      - configurationservice
    environment:
      CONFIGURATION_SERVICE_URL: http://configurationservice:7777
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka:8761/eureka